<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class LocationSeeder extends Seeder
{
    public function run()
    {
        $locations = [
            'AC-Castillejos',
            'BWPC-Pagudpud',
            'CONVERG-Calamba',
            'Converge - Lipa',
            'Converge-Cavite',
            'Converge-SJDM',
            'Convrg-Caloocan',
            'DUS - QC',
            'DUS-Angono',
            'DUS-Antipolo',
            'DUS-Balagtas',
            'DUS-Baliuag',
            'DUS-Batangas',
            'DUS-Cainta',
            'DUS-Caloocan',
            'DUS-Clark',
            'DUS-Dasmarinas',
            'DUS-Lucena',
            'DUS-Makati',
            'DUS-Malabon',
            'DUS-Malolos',
            'DUS-Manila',
            'DUS-Marikina',
            'DUS-Paranaque',
            'DUS-Pasay',
            'DUS-Pasig',
            'DUS-Plaridel',
            'DUS-SanPablo',
            'DUS-Sta.Maria',
            'DUS-StaRosa',
            'DUS-Tagaytay',
            'DUS-Valenzuela',
            'FAM-Pasig',
            'FOC-QC',
            'FPEI - Pitogo',
            'FPEI - Sangali',
            'GigaAce-Botolan',
            'GigaAce-Palauig',
            'Globe-Cebu',
            'GlobeN-Val',
            'Globe-StaMaria',
            'GNP-Mariveles',
            'HDD-Guiguinto',
            'HDD-Malolos',
            'HDD-Valenzuela',
            'HO-Renaissance',
            'Huawei-Baliwag',
            'Log-MarikinaCty',
            'LPC-BacolodLDN',
            'Meco - Pasig',
            'MECO-Aseana',
            'Meco-SJDMBulacn',
            'Meco-SnIldfonso',
            'Meco-TaguigCity',
            'Meco-Valenzuela',
            'MIDC-Caloocan',
            'MORE-SnIldfnso',
            'NGCP-AmlanNegOr',
            'NGCP-Antipolo',
            'NGCP-Bacolod',
            'NGCP-BBtgnLeyte',
            'NGCP-Bislig',
            'NGCP-Butuan',
            'NGCP-Cebu',
            'NGCP-Colon Cebu',
            'NGCP-LapuLapu',
            'NGCP-Mandaue',
            'NGCP-Naga Colon',
            'NGCP-Ormoc',
            'NGCP-Pitogo',
            'NGCP-TandagSDS',
            'PLDT - Cavite',
            'PLDT- QC',
            'PLDT-CabntuanNE',
            'PLDT-Laoag',
            'PLDT-Legazpi',
            'PLDT-Naga',
            'PLDT-PPSPalawan',
            'PLDT-Romblon',
            'PLDT-Sorsogon',
            'PLDT-Tiaong',
            'PLDT-Urdaneta',
            'Radius-Calamba',
            'Radius-Cavite',
            'Radius-QC',
            'SCSEI-SMrcelino',
            'Seconded MBI',
            'Seconded MLI',
            'SMC-EERI-Btngas',
            'SMC-Mariveles',
            'SP-CabanatuanNE',
            'SP-PeñarandaNE',
            'SP-StaRosaNE',
            'Telecom-QC',
            'TSPI-GapanNE',
            'UAM - QC',
            'UAM-San Pablo',
            'UAM-Sta. Rosa'
        ];

        foreach ($locations as $location) {
            DB::table('locations')->insert([
                'location_name' => $location,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
